### ISSUE TITLE
The webapp does not seem to accept the 'pm' and 'pmfile' parameters for '/pi' operation

### ISSUE THREAD

**Issue by lwiechec** [m0smith/malabar-mode-jar#32]

**Comment by m0smith** [comment]
I am updating the `malabar-mode-jar` to use gradle as well as maven.  The `malabar-mode` develop branch has been updated to use the new jar file.  Doing final check before releasing both.  I was going to wait until the gradle functionality was added but I'll push it so it is all working again.

**Comment by lwiechec** [comment]
Thanks Matthew for the update. Sorry that I rush things so fast but I found myself dependent more and more on `malabar-mode` in every day work; I thought about upgrading yesterday because I had version from January and thought upgrading is a good thing, especially that was the package from Melpa, so - official...

**Comment by m0smith** [comment]
Are you building the malabar-mode-jar from source?

**Comment by lwiechec** [comment]
Hi,Yes, to temporarily make the latest ‎version of malabar-mode work with the webapp, I built malabar-mode-jar from the source.                                                                                                                                                                                                                                                                                                                                         Lukasz Wiechec                                                                                                                                                                                                                From: Matthew O. SmithSent: Tuesday, 17 March 2015 17:16To: m0smith/malabar-mode-jarReply To: m0smith/malabar-mode-jarCc: Lukasz WiechecSubject: Re: [malabar-mode-jar] The webapp does not seem to accept the 'pm' and 'pmfile' parameters for '/pi' operation (#32)Are you building the malabar-mode-jar from source?

—Reply to this email directly or view it on GitHub.

**Comment by m0smith** [comment]
ok, that makes sense.  I have pushed both the jar file and the lisp code so the next update from MELPA should have this fixed.

**Comment by lwiechec** [comment]
Hi Matthew, Thanks for the info and for the update! I shall check it out.                                                                                                                                                                                                                                                                                                                                        Lukasz Wiechec                                                                                                                                                                                                                From: Matthew O. SmithSent: Wednesday, 18 March 2015 15:17To: m0smith/malabar-mode-jarReply To: m0smith/malabar-mode-jarCc: Lukasz WiechecSubject: Re: [malabar-mode-jar] The webapp does not seem to accept the 'pm' and 'pmfile' parameters for '/pi' operation (#32)ok, that makes sense.  I have pushed both the jar file and the lisp code so the next update from MELPA should have this fixed.

—Reply to this email directly or view it on GitHub.
